# Sử dụng Node.js 18
FROM node:18

# Thiết lập thư mục làm việc
WORKDIR /app

# Sao chép file package.json và cài đặt dependencies
COPY package.json package-lock.json ./
RUN npm install

# Sao chép toàn bộ project vào container
COPY . .

# Mở port 5173 để chạy Vite
EXPOSE 5173

# Chạy ứng dụng Vue.js
CMD ["npm", "run", "dev"]
