# docker-compose.yml
version: '3.8'

services:
  # Laravel App (PHP + Laravel)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app
    user: root
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www:delegated
      - ./backend/vendor:/var/www/vendor:cached
      - ./backend/storage:/var/www/storage:delegated
      - ./backend/bootstrap/cache:/var/www/bootstrap/cache:delegated
    environment:
      - APP_ENV=local
      - DB_HOST=mysql_db
      - REDIS_HOST=redis
      - PHP_OPCACHE_ENABLE=1
      - PHP_OPCACHE_MEMORY_CONSUMPTION=256
    depends_on:
      - db
      - redis
    networks:
      - laravel_network

  # MySQL 8
  db:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel_network

  # Redis Cache
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/public:cached
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - laravel_network

  # Node.js (Frontend with Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: vite_frontend
    restart: unless-stopped
    working_dir: /app
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/app:cached
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
    command: ["sh", "-c", "npm install && npm run dev -- --host"]
    depends_on:
      - app
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data: